version: 2
updates:
  # main
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot: Maven"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot: GitHub Actions"
    groups:
      github-actions:
        patterns:
          - "*"
  # 3.x
  - package-ecosystem: "github-actions"
    target-branch: "3.x"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot: GitHub Actions"
    groups:
      github-actions:
        patterns:
          - "*"
