name: Binary Compatibility

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  japicmp:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'

      - name: (`main` only) Compare with the latest release
        if: github.base_ref == null
        run: >
          ./mvnw -V --no-transfer-progress -e package japicmp:cmp
          -DskipTests
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true

      - name: (PR only) Checkout `${{ github.base_ref }}` into subfolder
        if: github.base_ref != null
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: ${{ github.run_id }}.${{ github.base_ref }}
      - name: (PR only) Build `${{ github.base_ref }}`
        if: github.base_ref != null
        run: ./mvnw -V --no-transfer-progress -e -f ${{ github.run_id }}.${{ github.base_ref }}/pom.xml package -DskipTests
      - name: (PR only) Compare `${{ github.head_ref }}` with `${{ github.base_ref }}`
        if: github.base_ref != null
        run: >
          ./mvnw -V --no-transfer-progress -e -Pjapicmp-branch package japicmp:cmp
          -DskipTests
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true
          -Djapicmp.oldVersion.basedir=${{ github.run_id }}.${{ github.base_ref }}
      - name: (PR only) Add label
        if: github.base_ref != null && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['binary incompatible']
            })
      - name: (PR only) Remove label
        if: github.base_ref != null && success()
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'binary incompatible'
            })

      - name: Print result
        if: success() || failure()
        run: cat target/japicmp/default-cli.diff
      - name: Upload reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: japicmp
          path: target/japicmp
          if-no-files-found: error
