name: Binary Compatibility

on:
  pull_request:
    paths:
      - 'assertj-core/**'
  push:
    paths:
      - 'assertj-core/**'

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always -DskipTests

jobs:
  verify-with-base:
    name: Verify with target branch
    runs-on: ubuntu-latest
    if: github.base_ref != null

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Checkout `${{ github.base_ref }}` into subfolder
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: ${{ github.run_id }}.${{ github.base_ref }}
      - name: Build `${{ github.base_ref }}`
        run: ./mvnw $MAVEN_ARGS -f ${{ github.run_id }}.${{ github.base_ref }}/assertj-core/pom.xml package
      - name: Compare `${{ github.head_ref }}` with `${{ github.base_ref }}`
        run: >
          ./mvnw $MAVEN_ARGS -f assertj-core/pom.xml -Pjapicmp-branch package japicmp:cmp
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true
          -Djapicmp.oldVersion.basedir=${{ github.run_id }}.${{ github.base_ref }}/assertj-core

      - name: Add label
        if: failure()
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['binary incompatible with: base']
            })

      - name: Remove label
        if: success()
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'binary incompatible with: base'
            })

      - name: Add result to job summary
        if: success() || failure()
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat assertj-core/target/japicmp/default-cli.diff >> $GITHUB_STEP_SUMMARY
      - name: Upload reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: japicmp
          path: assertj-core/target/japicmp
          if-no-files-found: error

  verify-with-release:

    name: Verify with latest release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Compare with the latest release
        run: >
          ./mvnw $MAVEN_ARGS -f assertj-core/pom.xml package japicmp:cmp
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true

      - name: Add label
        if: github.base_ref != null && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['binary incompatible with: release']
            })
      - name: Remove label
        if: github.base_ref != null && success()
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'binary incompatible with: release'
            })

      - name: Add result to job summary
        if: success() || failure()
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat assertj-core/target/japicmp/default-cli.diff >> $GITHUB_STEP_SUMMARY
      - name: Upload reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: japicmp
          path: assertj-core/target/japicmp
          if-no-files-found: error
