name: Binary Compatibility

on:
  push:
    branches: [ 'main', '3.x' ]
    paths: [ 'assertj-core/**' ]
  pull_request:
    branches: [ 'main', '3.x' ]
    paths: [ 'assertj-core/**' ]

permissions: {}

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always -DskipTests

jobs:
  verify-with-base:
    name: Verify with target branch
    runs-on: ubuntu-latest
    if: github.base_ref != null

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'

      - name: Checkout `${{ github.base_ref }}` into subfolder
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.base_ref }}
          path: ${{ github.run_id }}.${{ github.base_ref }}
      - name: Build `${{ github.base_ref }}`
        run: ./mvnw $MAVEN_ARGS -f ${{ github.run_id }}.${{ github.base_ref }}/assertj-core/pom.xml package
      - name: Compare `${{ github.head_ref }}` with `${{ github.base_ref }}`
        run: >
          ./mvnw $MAVEN_ARGS -f assertj-core/pom.xml -Pjapicmp-branch package japicmp:cmp
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true
          -Djapicmp.oldVersion.basedir=${{ github.run_id }}.${{ github.base_ref }}/assertj-core

      - name: Add result to job summary
        if: success() || failure()
        run: cat assertj-core/target/japicmp/default-cli.md >> $GITHUB_STEP_SUMMARY

  verify-with-release:

    name: Verify with latest release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'

      - name: Compare with the latest release
        run: >
          ./mvnw $MAVEN_ARGS -f assertj-core/pom.xml package japicmp:cmp
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true

      - name: Add result to job summary
        if: success() || failure()
        run: cat assertj-core/target/japicmp/default-cli.md >> $GITHUB_STEP_SUMMARY
